apiVersion: v1
kind: Pod
metadata:
  name: snyky
spec:
  containers:
  - name: snyky
    image: ericsmalling/snyky:23.0
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    imagePullPolicy: Always
