---
apiVersion: v1
kind: Namespace
metadata:
  name: secure
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.26
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: psp:secure:restricted
#  namespace: secure
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: psp:restricted
#subjects:
#- kind: Group
#  name: system:serviceaccounts
#  apiGroup: rbac.authorization.k8s.io
