on:
  pull_request:
    types: [review_requested]

jobs:
  review_request_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A review for the team '${{ github.event.requested_team.name }}' was requested"
